### PR TITLE
Finish release notes for v2.1.2

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@yshrsmz Awesome! I think the updates PR should wait until the bug-fix release gets shipped.

### CODE REVIEW

**Comment by yshrsmz** [comment]
yeah, sorry for being late.
will release the fix soon.
As AnrdoiX reached 1.0.0-rc1, I think we should move to AndroidX instead of using 28.0.0

**Comment by eclectice** [comment]
> yeah, sorry for being late.
> will release the fix soon.
> As AnrdoidX reached 1.0.0-rc1, I think we should move to AndroidX instead of using 28.0.0

Yes, please support AndroidX

**Comment by yshrsmz** [comment]
@eclectice yes will do. but if you are in a hurry, PR is　always welcome.

**Comment by SUPERCILEX** [comment]
We should start with the support library though because that's forwards compatible with AndroidX. You can use this library today with AndroidX.

**Comment by eclectice** [comment]
> We should start with the support library though because that's forwards compatible with AndroidX. You can use this library today with AndroidX.

I am not sure though with the current **2.1.2** release as I got this **incompatible types error** trying to assign **_androidx.recyclerview.widget.RecyclerView.Adapter_** instance with _**LicenceAdapte**r_ extended from **_android.support.v7.widget.RecyclerView.Adapter_** after migrating to AndroidX, which is expected.

**Comment by yshrsmz** [comment]
Are you sure that the jetfier is enabled correctly?
At least [my app is working as expected](https://github.com/yshrsmz/monotweety/blob/93a51794a2e1e6c93d56be84d8bf2dab4b6cef48/app/src/main/java/net/yslibrary/monotweety/license/LicenseController.kt#L83) with AndroidX and the latest LicenseAdapter.

**Comment by eclectice** [comment]
> Are you sure that the jetfier is enabled correctly?
> At least [my app is working fine](https://github.com/yshrsmz/monotweety/blob/93a51794a2e1e6c93d56be84d8bf2dab4b6cef48/app/src/main/java/net/yslibrary/monotweety/license/LicenseController.kt#L83) with AndroidX and the latest LicenseAdapter.

I followed what you did in your app as follows:
Changed gradle.properties:
```
android.useAndroidX = true
android.enableJetifier = true
```
Added into app's build.gradle the **androidx.recyclerview:recyclerview**:
```
ext.legacy_support_version = "1.0.0-rc02"
ext.material_version = "1.0.0-rc02"
...
dependencies {
...
implementation "com.google.android.material:material:$material_version"
implementation "androidx.appcompat:appcompat:$legacy_support_version"
implementation "androidx.recyclerview:recyclerview:$legacy_support_version"
implementation 'net.yslibrary.licenseadapter:licenseadapter:2.1.2'
...
}
```
But, I still got **incompatible types** error.

**Comment by SUPERCILEX** [comment]
What version of Android Studio are you running? And what about the Android Gradle Plugin?

**Comment by eclectice** [comment]
> What version of Android Studio are you running? And what about the Android Gradle Plugin?

```
Android Studio 3.1.4
Build #AI-173.4907809, built on July 24, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
```
buildscript {
    ....
    ext.gradle_plugin_version="3.1.4"
    ....
    dependencies {
        ....
        classpath "com.android.tools.build:gradle:$gradle_plugin_version"
        ....
    }
    ....
}
```

**Comment by yshrsmz** [comment]
Ah, this seems to be the cause.
I thinK Jetifier needs Android Gradle Plugin 3.2 or later

**Comment by eclectice** [comment]
> Ah, this seems to be the cause.
> I thinK Jetifier needs Android Gradle Plugin 3.2 or later

Oh, ok. That explains a lot. ;)

**Pull request merged**
